export enum SQFEffectLocality {
    LOCAL = "Local Effect",
    GLOBAL = "Global Effect",
}
export enum SQFArgumentLocality {
    LOCAL = "Local Argument",
    GLOBAL = "Global Argument",
}

export enum SQFCompletionItemKind {
    Text,
    Method,
    Function,
    Constructor,
    Field,
    Variable,
    Class,
    Interface,
    Module,
    Property,
    Unit,
    Value,
    Enum,
    Keyword,
    Snippet,
    Color,
    File,
    Reference,
    Folder,
    EnumMember,
    Constant,
    Struct,
    Event,
    Operator,
    TypeParameter,
}

export enum SQFCompletionItemTag {
    Deprecated = 1,
}

export interface IJSON<T> {
    [key: string]: T;
}

export enum SQFDataType {
    Empty = "EMPTY",
    Array = "ARRAY",
    Boolean = "BOOLEAN",
    Behaviour = "(Behaviour) STRING",
    CombatMode = "(Combat Mode) STRING",
    SpeedMode = "(Speed Mode) STRING",
    Formation = "(Formation) STRING",
    Code = "CODE",
    Config = "CONFIG",
    Control = "CONTROL",
    DiaryRecord = "DIARY-RECORD",
    Display = "DISPLAY",
    Exception = "EXCEPTION",
    EdenEntity = "EDEN-ENTITY",
    EdenId = "EDEN-ID",
    EditorObject = "EDITOR-OBJECT",
    Group = "GROUP",
    HashMap = "HASHMAP",
    Location = "LOCATION",
    Namespace = "NAMESPACE",
    Number = "NUMBER",
    NetObject = "NetObject",
    Object = "OBJECT",
    ScriptHandle = "SCRIPT-HANDLE",
    Side = "SIDE",
    String = "STRING",
    StructuredText = "STRUCTURED-TEXT",
    Task = "TASK",
    Team = "TEAM",
    TeamMember = "TEAM-MEMBER",
    Text = "TEXT",
    NaN = "NAN",
    Any = "ANYTHING",
    Nothing = "NOTHING",
    Void = "VOID",
    Marker = "(Marker) STRING",
    Vector = "(Vector) NUMBER[x,y,z]",
    Variable = "VARIABLE",
    IfType = "IF-TYPE",
    SwitchType = "SWITCH-TYPE",
    WhileType = "WHILE-TYPE",
    WithType = "WITH-TYPE",
    ForType = "FOR-TYPE",
    HashMapKey = "HASHMAP-KEY",
    Waypoint = "[GROUP,NUMBER]",
    Position = "(Position) NUMBER[x,y,z?]",
    Position3d = "(Position3D) NUMBER[x,y,z]",
    Position2d = "(Position2D) NUMBER[x,y]",
    PositionWorld = "(PositionWorld) NUMBER[x,y,z]",
    PositionASL = "(PositionASL) NUMBER[x,y,z]",
    PositionAGL = "(PositionAGL) NUMBER[x,y,z]",
    PositionAGLS = "(PositionAGLS) NUMBER[x,y,z]",
    PositionATL = "(PositionATL) NUMBER[x,y,z]",
    PositionASLW = "(PositionASLW) NUMBER[x,y,z]",
    PositionConfig = "(PositionConfig) NUMBER[x,z,y]",
    PositionRelative = "(PositionRelative) NUMBER[x,z,y]",
    ParticleArray = `(Particle) ARRAY`,
    Color = "(Color) NUMBER[R,G,B]",
    ColorAlpha = "(Color) NUMBER[R,G,B,A]",
    MinMidMax = "(Random) NUMBER[min,mid,max]",
    UnitLoadout = "(Unit-Loadout) ARRAY",
}

// TODO: there may still be some value in having this information
export enum SQFGrammarType {
    Function = "function",
    AccessModifier = "access-modifier",
    ManipulativeOperator = "manipulative-operator",
    ControlStatement = "control-statement",
    ConditionOperator = "condition-operator",
    ComparisonOperator = "comparison-operator",
    ReservedLiteral = "reserved-literal",
    BooleanLiteral = "boolean-literal",
    NullLiteral = "null-literal",
    PropertyAccessor = "property-accessor",
    Command = "command",
    StringCompiler = "string-compiler",
    FileCompiler = "file-compiler",
    FileExecutor = "file-executor",
    CodeExecutor = "code-executor",
    PreprocessorCommand = "preprocessor-command",
    NamespaceLiteral = "namespace",
}

export interface SQFItemConfig {}
